# Generated by Django 3.1.4 on 2020-12-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBShorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('movie_name', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=10)),
                ('info', models.CharField(max_length=300)),
                ('star', models.CharField(max_length=5)),
            ],
        ),
    ]
