# Generated by Django 3.1.4 on 2020-12-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbshorts',
            name='info',
            field=models.CharField(max_length=500),
        ),
    ]
