# Generated by Django 3.1.4 on 2020-12-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201219_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbshorts',
            name='movie_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dbshorts',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
    ]
